# -*- coding: utf-8 -*-
"""test_llm_gateway.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBY76bG_bAcwCj0qw6u3buYniQUj49wx

# Stage 1: Single Agent (Tools and Tool Schema)

## Install dependencies
Run this once in a fresh environment.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install langgraph langchain-openai python-dotenv langchain_ollama

"""## 1) Imports"""

import os
from dotenv import load_dotenv
from typing import Any, Dict, Literal
from typing import TypedDict, Annotated, List
from langchain_openai import ChatOpenAI
from langchain_core.messages import AnyMessage
from langgraph.graph import StateGraph, START
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode, tools_condition
from langchain_core.tools import tool
from langchain_ollama import ChatOllama

"""## 2) Load environment variables - please read instructions carefully"""

# if you are running in local, uncomment below line. also make sure you shall have a .env file
load_dotenv()

# if you are running in google colab, uncomment below line. and replace "Your_API_Key" with your own openAI API key
#os.environ["OPENAI_API_KEY"] = "Your_API_Key"

"""## 3) System prompt"""

SYSTEM = """You are a travel planning agent.

Rules:
- Ask clarifying questions only when essential info is missing.
- Do not invent facts. Use search tool for fresh facts when needed.
- When user asks "total cost", ALWAYS call estimate_trip_cost with the latest trip parameters from conversation.
- If user says "add additional one day trip", interpret as +1 day unless they explicitly say it replaces an existing day.


Output format:
1) Total cost (with assumptions)
"""

SYSTEM = """You are a travel cost estimation agent.

Output format:
1) Total cost (with assumptions)
"""

# Tool-calling instructions sent as part of the user message (not system prompt).
# Useful when the gateway overrides or ignores the system prompt.
TOOL_CALL_INSTRUCTIONS = """
When the user asks for a cost estimate, you MUST first reply with ONLY this JSON and nothing else:
{"tool": "estimate_trip_cost", "args": {"destination": "<str>", "days": <int>, "travelers": <int>, "comfort": "<budget|mid|premium>"}}
Do not invent cost figures. After you receive the tool result, present it to the user.
"""

"""## 4) Tool - estimate trip cost"""

@tool
def estimate_trip_cost(
    destination: str,
    days: int,
    travelers: int,
    comfort: str = "mid",
    #comfort: Literal["budget", "mid", "premium"] = "mid"
) -> Dict[str, Any]:
    """
    Estimate a rough trip budget (SGD) using simple heuristics.
    comfort: budget | mid | premium
    Returns a breakdown and total estimate in SGD.
    """
    if days <= 0 or travelers <= 0:
        raise ValueError("days and travelers must be > 0")

    comfort = comfort.lower().strip()
    if comfort not in {"budget", "mid", "premium"}:
        raise ValueError("comfort must be one of: budget, mid, premium")

    # Very rough per-person-per-day estimates (SGD) excluding flights
    lodging_pppd = {"budget": 60, "mid": 140, "premium": 300}[comfort]
    food_pppd = {"budget": 30, "mid": 60, "premium": 120}[comfort]
    local_transport_pppd = {"budget": 10, "mid": 20, "premium": 50}[comfort]
    activities_pppd = {"budget": 20, "mid": 50, "premium": 120}[comfort]

    lodging = lodging_pppd * travelers * days
    food = food_pppd * travelers * days
    transport = local_transport_pppd * travelers * days
    activities = activities_pppd * travelers * days

    subtotal = lodging + food + transport + activities
    contingency = round(subtotal * 0.12)  # 12% buffer
    total = subtotal + contingency

    return {
        "destination": destination,
        "days": days,
        "travelers": travelers,
        "comfort": comfort,
        "currency": "SGD",
        "breakdown": {
            "lodging": lodging,
            "food": food,
            "local_transport": transport,
            "activities": activities,
            "contingency": contingency,
        },
        "total_estimate": total,
        "note": "Heuristic estimate excludes international flights/insurance/visa fees.",
    }

"""## helper function - Pretty Print"""

def pretty_print(response):
    last_msg = response["messages"][-1]

    if isinstance(last_msg.content, list):
        text = "".join(
            block["text"]
            for block in last_msg.content
            if block.get("type") == "text"
        )
    else:
        text = last_msg.content

    print(text)

"""## 5) Build the LangGraph agent loop"""

class State(TypedDict):
    # add_messages makes state["messages"] append-only and compatible with tool loops
    messages: Annotated[List[AnyMessage], add_messages]

tools = [estimate_trip_cost]
web_tool = {"type": "web_search_preview"}  # LangChain docs use web_search_preview

# LLM gateway configuration - loaded from .env (see README.md)
LLM_GATEWAY_URL = os.getenv("LLM_GATEWAY_URL")
LLM_GATEWAY_API_KEY = os.getenv("LLM_GATEWAY_API_KEY")
LLM_MODEL = os.getenv("LLM_MODEL")

if not all([LLM_GATEWAY_URL, LLM_GATEWAY_API_KEY, LLM_MODEL]):
    raise EnvironmentError(
        "Missing required env vars. Please create a .env file with:\n"
        "  LLM_GATEWAY_URL, LLM_GATEWAY_API_KEY, LLM_MODEL\n"
        "See README.md for details."
    )

llm = ChatOllama(
    model=LLM_MODEL,
    base_url=LLM_GATEWAY_URL,
    temperature=0.4,
    num_predict=2000,
    client_kwargs={
        "headers": {
            "X-API-Key": LLM_GATEWAY_API_KEY
        }
    }
)

# llm = ChatOpenAI(
#     model="gpt-4.1-mini",
#     api_key=os.getenv("OPENAI_API_KEY"),
#     temperature=0.4
# )

# llm_with_tools = llm.bind_tools([web_tool] + tools)
llm_with_tools = llm.bind_tools(tools)

def chatbot(state: State):
    # The LLM sees prior messages for this thread via checkpointer
    # We do NOT hardcode tool list in SYSTEM; tool schemas are in bind_tools.
    return {"messages": [llm_with_tools.invoke(state["messages"])]}

builder = StateGraph(State)
builder.add_node("chatbot", chatbot)
builder.add_node("tools", ToolNode(tools))

builder.add_edge(START, "chatbot")
builder.add_conditional_edges("chatbot", tools_condition)  # routes to "tools" when tool calls exist
builder.add_edge("tools", "chatbot")  # tool result goes back to model for next step, this line shall be uncommented for the program to work

graph = builder.compile()

from IPython.display import Image, display
display(Image(graph.get_graph().draw_mermaid_png()))

"""## 4) Run

Manual tool-call loop: the gateway has no native tool support, so the model
emits a JSON tool request which we parse and execute ourselves.
"""

import json
import re

def extract_tool_call(text: str):
    """Return {"tool": ..., "args": {...}} if the model emitted a tool request."""
    match = re.search(r'\{.*"tool".*\}', text, re.DOTALL)
    if not match:
        return None
    try:
        payload = json.loads(match.group(0))
    except json.JSONDecodeError:
        return None
    if payload.get("tool") and isinstance(payload.get("args"), dict):
        return payload
    return None

import time

def invoke_with_retry(messages, max_retries=5, backoff=3):
    """Retry llm.invoke on transient gateway errors (ALB rate-limits rapid successive calls)."""
    for attempt in range(1, max_retries + 1):
        try:
            return llm.invoke(messages)
        except Exception as e:
            if attempt == max_retries:
                raise
            wait = backoff * attempt
            print(f">>> Attempt {attempt} failed ({type(e).__name__}), retrying in {wait}s...")
            time.sleep(wait)

def run_agent(user_msg: str):
    messages = [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": TOOL_CALL_INSTRUCTIONS + "\n" + user_msg},
    ]
    for _ in range(4):  # max iterations
        reply = invoke_with_retry(messages)
        tool_req = extract_tool_call(reply.content)
        if not tool_req:
            return reply.content  # final answer
        print(f">>> Tool request: {tool_req}")
        result = estimate_trip_cost.invoke(tool_req["args"])
        print(f">>> Tool result: {result}")
        messages.append({"role": "assistant", "content": reply.content})
        messages.append({"role": "user", "content": f"Tool result: {json.dumps(result)}\nNow present the estimate to the user."})
    return "Max tool-call iterations reached."

msg = "Plan a 2-day Tokyo trip for 2 adults. Mid comfort. how much will be the cost"
print(run_agent(msg))

"""## Tool Schema

- in day 1 example, without framework, developer needs to write the tool schema below.
- with @tool, langchain automatically generate the tool schema.
"""

# tools = [
#     {
#         "type": "function",
#         "function": {
#             "name": "estimate_trip_cost",
#             "description": "Estimate a rough trip budget (SGD) using simple heuristics. comfort: budget | mid | premium. Returns a breakdown and total estimate in SGD.",
#             "parameters": {
#                 "type": "object",
#                 "properties": {
#                     "days": {
#                         "type": "integer",
#                         "description": "Number of travel days"
#                     },
#                     "travelers": {
#                         "type": "integer",
#                         "description": "Number of travelers"
#                     },
#                     "comfort": {
#                         "type": "string",
#                         "description": "Travel comfort level",
#                         "enum": ["budget", "mid", "premium"],
#                         "default": "mid"
#                     }
#                 },
#                 "required": ["days", "travelers"]
#             }
#         }
#     }
# ]

from langchain_core.utils.function_calling import convert_to_openai_tool

tool_schema = convert_to_openai_tool(
    estimate_trip_cost
)

from pprint import pprint
pprint(tool_schema)
